// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/hellostreamingworld.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Hellostreamingworld {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class MultiGreeter
  {
    static readonly string __ServiceName = "hellostreamingworld.MultiGreeter";

    static readonly grpc::Marshaller<global::Hellostreamingworld.HelloRequest> __Marshaller_hellostreamingworld_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Hellostreamingworld.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Hellostreamingworld.HelloReply> __Marshaller_hellostreamingworld_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Hellostreamingworld.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Hellostreamingworld.HelloRequest, global::Hellostreamingworld.HelloReply> __Method_sayHello = new grpc::Method<global::Hellostreamingworld.HelloRequest, global::Hellostreamingworld.HelloReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "sayHello",
        __Marshaller_hellostreamingworld_HelloRequest,
        __Marshaller_hellostreamingworld_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Hellostreamingworld.HellostreamingworldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MultiGreeter</summary>
    [grpc::BindServiceMethod(typeof(MultiGreeter), "BindService")]
    public abstract partial class MultiGreeterBase
    {
      /// <summary>
      /// Sends multiple greetings
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task sayHello(global::Hellostreamingworld.HelloRequest request, grpc::IServerStreamWriter<global::Hellostreamingworld.HelloReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MultiGreeter</summary>
    public partial class MultiGreeterClient : grpc::ClientBase<MultiGreeterClient>
    {
      /// <summary>Creates a new client for MultiGreeter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MultiGreeterClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MultiGreeter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MultiGreeterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MultiGreeterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MultiGreeterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends multiple greetings
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Hellostreamingworld.HelloReply> sayHello(global::Hellostreamingworld.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return sayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends multiple greetings
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Hellostreamingworld.HelloReply> sayHello(global::Hellostreamingworld.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_sayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MultiGreeterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MultiGreeterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MultiGreeterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_sayHello, serviceImpl.sayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MultiGreeterBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_sayHello, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Hellostreamingworld.HelloRequest, global::Hellostreamingworld.HelloReply>(serviceImpl.sayHello));
    }

  }
}
#endregion
